name: GitHub Actions
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: install modules
        run: yarn
      - name: build project
        run: yarn build
      - name: lint test
        run: yarn lint
